global:
  scrape_interval:     5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
  - job_name: 'metrics'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: 
        - host.docker.internal:2112
        - host.docker.internal:2113
        - host.docker.internal:2114
